#!/usr/bin/env python3
"""
CROSPI -> Trossen arm_controller bridge for WidowX eTaSL tasks.
Subscribe to the expected joint states from CROSPI and publish them to Trossen's JointTrajectoryController.
"""
import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient
from rclpy.qos import QoSProfile, ReliabilityPolicy
from sensor_msgs.msg import JointState
from control_msgs.action import FollowJointTrajectory
from trajectory_msgs.msg import JointTrajectoryPoint
from builtin_interfaces.msg import Duration

JOINT_NAMES = [
    'joint_0',
    'joint_1',
    'joint_2',
    'joint_3',
    'joint_4',
    'joint_5',
]

class CROSPiBridge(Node):
    def __init__(self):
        super().__init__('crospi_bridge')

        # Subscriber to CROSPI joint states (BEST_EFFORT to match CROSPI publisher QoS)
        qos = QoSProfile(depth=10, reliability=ReliabilityPolicy.BEST_EFFORT)
        self.sub = self.create_subscription(
            JointState,
            '/crospi/joint_states',
            self.on_desired_joints,
            qos
        )

        # connect arm_controller of Trossen
        self.action_client = ActionClient(self, FollowJointTrajectory, '/arm_controller/follow_joint_trajectory')

        self.get_logger().info('CROSPI Bridge node initialized, waiting for arm_controller...')
        self.action_client.wait_for_server()
        self.get_logger().info('Connected to arm_controller action server.')
    
    def on_desired_joints(self, msg: JointState):
        """every time we receive a new desired joint state from CROSPI, send it to the Trossen controller"""
        goal = FollowJointTrajectory.Goal()
        goal.trajectory.joint_names = JOINT_NAMES

        point = JointTrajectoryPoint()
        # only focus on the joints we care about
        positions = []
        for joint_name in JOINT_NAMES:
            if joint_name in msg.name:
                idx = msg.name.index(joint_name)
                positions.append(msg.position[idx])
            else:
                self.get_logger().warn(f"Joint {joint_name} not found in CROSPI message, using 0.0 as default")
                positions.append(0.0)  # default to 0 if not found
        
        point.positions = positions
        point.time_from_start = Duration(sec=0, nanosec=20_000_000)  # 20ms to reach the target, can be tuned
        goal.trajectory.points = [point]

        self.action_client.send_goal_async(goal)

def main():
    rclpy.init()
    node = CROSPiBridge()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()